version: "3.9"  # optional since v1.27.0
services:
  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    expose:
      - "5432"
      - "9000"
    ports:
      - "5432:5432"
      - "9000:8080"
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: bitnami1
      KEYCLOAK_HTTP_PORT: 8062
      KEYCLOAK_DATABASE_HOST: keycloak-db
      KEYCLOAK_DATABASE_PASSWORD: example
  keycloak-db:
    image: postgres
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bitnami_keycloak
  # auction-house:
  #   build: auction-house/.
  #   ports:
  #     - "8081:8081"
    environment:
      EUREKA_CLIENT_URL: http://football-sim-eureka:8761/eureka
      OAUTH_INTROSPECT_URL: http://keycloak:9000/auth/realms/master/protocol/openid-connect/token/introspect
  football-sim-eureka:
    build: football-sim-eureka/.
    ports:
      - "8761:8761"
  # football-sim-gateway:
  #   build: football-sim-gateway/.
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     EUREKA_CLIENT_URL: http://football-sim-eureka:8761/eureka
  #     OAUTH_INTROSPECT_URL: http://keycloak:9000/auth/realms/master/protocol/openid-connect/token/introspect