spring:
  application:
    name: football-sim-coach-manangement
  webflux:
    base-path: /football-sim-coach-manangement
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${OAUTH_INTROSPECT_URL:http://keycloak:9000/auth/realms/master/protocol/openid-connect/token/introspect}
          client-id: football-sim-test
          client-secret: 4X1h0FEPp04x4z6MmWyJcMN1xppuKbm4
  h2: 
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${DATASOURCE_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}