CREATE TABLE coach (
    COACH_ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    STATUS VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL, 
    LAST_MODIFIED_DATE TIMESTAMP
);
