spring:
  application:
    name: auction-house
  webflux:
    base-path: /auction-house
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${OAUTH_INTROSPECT_URL:http://keycloak:9000/auth/realms/master/protocol/openid-connect/token/introspect}
          client-id: football-sim-test
          client-secret: 4X1h0FEPp04x4z6MmWyJcMN1xppuKbm4
  h2: 
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}