spring:
  application:
    name: auction-house
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://keycloak/auth/realms/master/protocol/openid-connect/token/introspect
          client-id: football-sim-test
          client-secret: glE7WR7DTHg7HFxaPYr0wRwTM7NgnydJ
  h2: 
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
server:
  port: 8081
  servlet:
    context-path: /auction-house
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}