CREATE TABLE recruit (
    RECRUIT_ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL, 
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE TABLE bid (
    BID_ID VARCHAR(255) PRIMARY KEY,
    AMOUNT NUMERIC NOT NULL,
    RECRUIT_ID VARCHAR(255) NOT NULL, 
    USER_ID VARCHAR(255) NOT NULL, 
    STATUS VARCHAR(25) NOT NULL, 
    CREATED_DATE TIMESTAMP NOT NULL, 
    LAST_MODIFIED_DATE TIMESTAMP
);