spring:
  application:
    name: football-sim-gateway
  main:
   web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${OAUTH_INTROSPECT_URL:http://keycloak:9000/auth/realms/master/protocol/openid-connect/token/introspect}
          client-id: football-sim-test
          client-secret: 4X1h0FEPp04x4z6MmWyJcMN1xppuKbm4
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
      - id: auction-house
        uri: lb://auction-house
        predicates:
        - Path=/auction-house/**
        filters:
          - TokenRelay=
      - id: coach-management
        url: lb://football-sim-coach-management
        predicates:
        - Path=/football-sim-coach-management/**
        filters:
          - TokenRelay=
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}