spring:
  application:
    name: football-sim-gateway
  main:
   web-application-type: reactive
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
      - id: auction-house
        uri: lb://auction-house
        predicates:
        - Path=/auction-house/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka/}