spring:
  main:
   web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: auction-house
        uri: http://localhost:8081/auction-house
        predicates:
        - Path=/auction-house/**